stages:
  - deploy
  - build

variables:
  REGISTRY: "registry.gitlab.internal.garflak.com"
  IMAGE_NAME: "development/realm_of_echoes"

deploy-frontend-cloudflare:
  stage: deploy
  image: node:20-alpine
  script:
    - npm install -g wrangler
    - wrangler pages deploy . --project-name=realm-of-echoes
  environment:
    name: production
  only:
    - main

build-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/ssl/certs
    - cat "${FREEIPA_CA_CERT}" >> /kaniko/ssl/certs/ca-certificates.crt

    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${REGISTRY}/${IMAGE_NAME}:${CI_COMMIT_SHA}"
      --destination "${REGISTRY}/${IMAGE_NAME}:${CI_COMMIT_REF_SLUG}"
  tags:
    - docker
    - linux

build-chat-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/ssl/certs
    - cat "${FREEIPA_CA_CERT}" >> /kaniko/ssl/certs/ca-certificates.crt

    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/chat-server"
      --dockerfile "${CI_PROJECT_DIR}/chat-server/Dockerfile"
      --destination "${REGISTRY}/${IMAGE_NAME}/chat:${CI_COMMIT_SHA}"
      --destination "${REGISTRY}/${IMAGE_NAME}/chat:${CI_COMMIT_REF_SLUG}"
  tags:
    - docker
    - linux
