# k8s/helm/values.yaml
image:
  repository: registry.gitlab.internal.garflak.com/development/realm_of_echoes
  tag: latest # ArgoCD will overwrite this with the commit SHA

ingress:
  internalHost: echoes.apps.internal.garflak.com # ArgoCD will overwrite this
  externalHost: echoes.local # ArgoCD will overwrite this
