# k8s/helm/templates/registry-secret.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-games-sa

---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend-games
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-games-role"
          serviceAccountRef:
            name: "eso-games-sa"

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-registry-auth-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-games
    kind: SecretStore
  target:
    name: gitlab-registry-auth
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "registry.gitlab.internal.garflak.com": {
                "username": "{{ `{{ .username }}` }}",
                "password": "{{ `{{ .password }}` }}",
                "auth": "{{ `{{ printf "%s:%s" .username .password | b64enc }}` }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: games/registry
        property: username
    - secretKey: password
      remoteRef:
        key: games/registry
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-auth-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-games
    kind: SecretStore
  target:
    name: supabase-auth-secret
  data:
    - secretKey: SUPABASE_URL
      remoteRef:
        key: games/supabase
        property: SUPABASE_URL
    - secretKey: SUPABASE_SERVICE_ROLE_KEY
      remoteRef:
        key: games/supabase
        property: SUPABASE_SERVICE_ROLE_KEY
